name: Build and release on github

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    name: Create release tag
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: ncipollo/release-action@v1
        name: Create new Release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}